// Generated by nitro

import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/driverInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverInfo').default>>>>
    }
    '/api/getImagePath': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getImagePath').default>>>>
    }
    '/api/login_api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login_api').default>>>>
    }
    '/api/passengerInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passengerInfo').default>>>>
    }

    '/api/tables': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tables').default>>>>
    }
    '/api/update-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update-password').default>>>>
    }
    '/api/user-type': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user-type').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}