// Generated by nitro
<<<<<<< HEAD
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/driverInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverInfo').default>>>>
    }
=======
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/addDriverInvite': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/addDriverInvite').default>>>>
    }
    '/api/driverInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverInfo').default>>>>
    }
    '/api/driverInvites': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverInvites').default>>>>
    }
    '/api/driverUsers': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverUsers').default>>>>
    }
>>>>>>> story6
    '/api/getImagePath': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getImagePath').default>>>>
    }
    '/api/login_api': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login_api').default>>>>
    }
    '/api/passengerInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passengerInfo').default>>>>
    }
<<<<<<< HEAD
    '/api/tables': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tables').default>>>>
    }
    '/api/update-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update-password').default>>>>
    }
=======
    '/api/sendEmail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sendEmail').default>>>>
    }
    '/api/tables': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tables').default>>>>
    }
    '/api/trocaSenha': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trocaSenha').default>>>>
    }
    '/api/update-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update-password').default>>>>
    }
    '/api/updateUserPay': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/updateUserPay').default>>>>
    }
>>>>>>> story6
    '/api/user-type': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user-type').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}