// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/driverInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/driverInfo').default>>>>
    }
    '/api/getImagePath': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getImagePath').default>>>>
    }
    '/api/passengerInfo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/passengerInfo').default>>>>
    }
    '/api/trocaSenha': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trocaSenha').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}